"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z)dpflb)hr!e%*bx#k@*%-np=b6b)jd!0yrw&1@^+91(_aa_j&'

# SECURITY WARNING: don't run with debug turned on in production!
# ketika production tampilkan false ketika proses debug tampilkan debug = True
DEBUG = True
if DEBUG is True:
    ALLOWED_HOSTS = []
else:
    ALLOWED_HOSTS = ["127.0.0.1","*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'account',
    'blog',
    'kontak',
    'taggit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ID' #bahasa indonesia

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/



# URL prefix untuk mengakses file static (CSS, JS, gambar yang tidak berubah)
STATIC_URL = 'static/'
if DEBUG:
    STATICFILES_DIRS = [
        BASE_DIR / 'static'  # Path folder static utama di root project
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR / 'static')

# URL prefix untuk mengakses file media (file upload dari user)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR / 'media')
# Lokasi folder tempat menyimpan file media yang diupload user
# MEDIA_ROOT = BASE_DIR / 'media'

# Mengganti model user default Django dengan model kustom 'User' di app 'account'
AUTH_USER_MODEL = 'account.User'

# URL tujuan setelah login dan logout berhasil (redirect ke halaman index di app blog)
LOGIN_REDIRECT_URL = 'blog:blog_index'
LOGOUT_REDIRECT_URL = 'accounts:index'

# Email backend untuk pengiriman email (gunakan console backend untuk pengembangan)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# parameter smtp host,port, host_user, host_password
EMAIL_HOST = 'smtp.gmail.com' #STRING
EMAIL_PORT = 587 # INTEGER
EMAIL_HOST_USER = 'ikhsansudiramubaroq2910@gmail.com' #STRING
EMAIL_HOST_PASSWORD = 'hsxgwwgpafsfkmkz' #STRING password aplikasi
EMAIL_USE_TLS = True #BOOLEAN




# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
