# Generated by Django 5.2.5 on 2025-09-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontak', '0002_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Nama Lengkap'),
        ),
    ]
